USE [master]
GO
/****** Object:  Database [Filmdb]    Script Date: 29-04-2024 12:42:33 ******/
CREATE DATABASE [Filmdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Filmdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.DYLAN_DB24\MSSQL\DATA\Filmdb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Filmdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.DYLAN_DB24\MSSQL\DATA\Filmdb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Filmdb] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Filmdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Filmdb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Filmdb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Filmdb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Filmdb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Filmdb] SET ARITHABORT OFF 
GO
ALTER DATABASE [Filmdb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Filmdb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Filmdb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Filmdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Filmdb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Filmdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Filmdb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Filmdb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Filmdb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Filmdb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Filmdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Filmdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Filmdb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Filmdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Filmdb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Filmdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Filmdb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Filmdb] SET RECOVERY FULL 
GO
ALTER DATABASE [Filmdb] SET  MULTI_USER 
GO
ALTER DATABASE [Filmdb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Filmdb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Filmdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Filmdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Filmdb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Filmdb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Filmdb', N'ON'
GO
ALTER DATABASE [Filmdb] SET QUERY_STORE = ON
GO
ALTER DATABASE [Filmdb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Filmdb]
GO
/****** Object:  User [FilmProvider]    Script Date: 29-04-2024 12:42:33 ******/
CREATE USER [FilmProvider] FOR LOGIN [FilmProvider] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  User [FilmManager]    Script Date: 29-04-2024 12:42:33 ******/
CREATE USER [FilmManager] FOR LOGIN [FilmManager] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[Film]    Script Date: 29-04-2024 12:42:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Film](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Titel] [varchar](50) NULL,
	[Instruktør] [varchar](20) NULL,
	[Spilletid] [int] NULL,
	[Dato] [date] NULL,
	[Genre] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FilmSkuespiller]    Script Date: 29-04-2024 12:42:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FilmSkuespiller](
	[FilmID] [int] NOT NULL,
	[SkuespillerID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[FilmID] ASC,
	[SkuespillerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Genre]    Script Date: 29-04-2024 12:42:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Genre](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[GenreNavn] [varchar](30) NULL,
	[Beskrivelse] [varchar](120) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Skuespiller]    Script Date: 29-04-2024 12:42:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Skuespiller](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[navn] [varchar](30) NULL,
	[Portræt] [varchar](4) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Film]  WITH CHECK ADD FOREIGN KEY([Genre])
REFERENCES [dbo].[Genre] ([ID])
GO
ALTER TABLE [dbo].[FilmSkuespiller]  WITH CHECK ADD FOREIGN KEY([FilmID])
REFERENCES [dbo].[Film] ([ID])
GO
ALTER TABLE [dbo].[FilmSkuespiller]  WITH CHECK ADD FOREIGN KEY([SkuespillerID])
REFERENCES [dbo].[Skuespiller] ([ID])
GO
ALTER TABLE [dbo].[Film]  WITH CHECK ADD CHECK  (([Spilletid]>(0) AND [Spilletid]<=(180)))
GO
USE [master]
GO
ALTER DATABASE [Filmdb] SET  READ_WRITE 
GO
